# syntax=docker/dockerfile:1

ARG VERSION="2.8.6"
ARG VERSION_FULL="2.8.6.23-linux64"
ARG SDK_BUILD="20191127_152327"

# ARG VERSION="2.8.7/Python+SDK"
# ARG VERSION_FULL="2.8.7.4-linux64"
# ARG SDK_BUILD="20210819_141148"
# ARG VERSION="2.8.5"
# ARG VERSION_FULL="2.8.5.10-linux64"
# ARG SDK_BUILD="20181203_200915"


FROM ubuntu:xenial as tmp

ARG VERSION
ARG VERSION_FULL
ARG SDK_BUILD

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget -O /tmp/pynaoqi-python.tar.gz "https://community-static.aldebaran.com/resources/${VERSION}/pynaoqi-python2.7-${VERSION_FULL}-${SDK_BUILD}.tar.gz" \
    && tar -C /opt -xf /tmp/pynaoqi-python.tar.gz \
    && ln -sf /opt/pynaoqi-python2.7-${VERSION_FULL}-${SDK_BUILD} /opt/pynaoqi-python-sdk \
    && rm /tmp/pynaoqi-python.tar.gz

RUN wget -O /tmp/choregraphe-suite.tar.gz "https://community-static.aldebaran.com/resources/${VERSION}/choregraphe-suite-${VERSION_FULL}.tar.gz" \
    && tar -C /opt -xf /tmp/choregraphe-suite.tar.gz \
    && rm /tmp/choregraphe-suite.tar.gz

RUN wget -O /tmp/robot-settings.tar.gz "https://community-static.aldebaran.com/resources/${VERSION}/robot-settings-${VERSION_FULL}.tar.gz" \
    && tar -C /opt -xf /tmp/robot-settings.tar.gz \
    && rm /tmp/robot-settings.tar.gz

# RUN wget -O /tmp/naoqi-sdk.tar.gz "https://community-static.aldebaran.com/resources/2.8.6/naoqi-sdk/naoqi-sdk-${VERSION}.tar.gz" \
#     && tar -C /opt -xf /tmp/naoqi-sdk.tar.gz \
#     && rm /tmp/naoqi-sdk.tar.gz


FROM ubuntu:xenial as naoqi
# FROM ubuntu:trusty

ARG VERSION_FULL

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    build-essential \
    dbus \
    vim \
    python \
    python-dev \
    python-pip \
    python-setuptools \
    # libssl-dev \
    libxcb* \
    libgl-dev \
    libxrandr-dev \
    libxkbcommon-x11-dev \
    libfontconfig-dev \
    libxaw7-dev \
    libogre-1.9-dev \
    && rm -rf /var/lib/apt/lists/*


ARG uid=2001
ARG gid=2860

WORKDIR /app
RUN groupadd -g ${gid} naoqi && useradd -m --no-log-init -r -u ${uid} -g naoqi naoqi
RUN chown naoqi:naoqi /app

COPY --from=tmp --chown=naoqi:naoqi /opt /opt
RUN ln -fs /opt/choregraphe-suite-${VERSION_FULL}/monitor /usr/bin/monitor \
    && ln -fs /opt/choregraphe-suite-${VERSION_FULL}/choregraphe /usr/bin/choregraphe \
    && ln -fs /opt/robot-settings-${VERSION_FULL}/robot_settings /usr/bin/robot_settings \
    && ln -sf /usr/lib/x86_64-linux-gnu/OGRE-1.9.0 /opt/pynaoqi-python-sdk/lib/OGRE


USER naoqi:naoqi

ENV PYTHONPATH "${PYTHONPATH}:/opt/pynaoqi-python-sdk/lib/python2.7/site-packages"
#ENV QI_SDK_PREFIX="/opt/pynaoqi-python-sdk"
#ENV LIBGL_ALWAYS_INDIRECT=1
#ENV QT_DEBUG_PLUGINS=1
# RUN pip install --upgrade pip==20.3.4


CMD ["bash"]
# CMD ["choregraphe", "--key 654e-4564-153c-6518-2f44-7562-206e-4c60-5f47-5f45"]
